// <auto-generated />
using EatInOslo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace EatInOslo.Migrations
{
    [DbContext(typeof(EatInOsloContext))]
    partial class EatInOsloContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("EatInOslo.Models.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("RestaurantID");

                    b.Property<string>("description");

                    b.Property<string>("imgurl");

                    b.HasKey("ID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("EatInOslo.Models.Restaurant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<string>("imgurl");

                    b.Property<string>("name");

                    b.Property<string>("type");

                    b.HasKey("ID");

                    b.ToTable("Restaurant");
                });

            modelBuilder.Entity("EatInOslo.Models.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("RestaurantID");

                    b.Property<int?>("UserID");

                    b.Property<string>("text");

                    b.Property<string>("title")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("UserID");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("EatInOslo.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("EatInOslo.Models.Image", b =>
                {
                    b.HasOne("EatInOslo.Models.Restaurant", "Restaurant")
                        .WithMany("Image")
                        .HasForeignKey("RestaurantID");
                });

            modelBuilder.Entity("EatInOslo.Models.Review", b =>
                {
                    b.HasOne("EatInOslo.Models.Restaurant", "Restaurant")
                        .WithMany("Review")
                        .HasForeignKey("RestaurantID");

                    b.HasOne("EatInOslo.Models.User", "User")
                        .WithMany("Review")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
